# TD sur pandas

# 0) import de la librairie

In [1]:
import pandas as pd

# 1) création d'une dataframe

In [13]:
url = "https://www.data.gouv.fr/fr/datasets/r/b4f8dbb9-9a4d-4203-bd6d-ba26615fa8ee"
url ="https://donneespubliques.meteofrance.fr/donnees_libres/Txt/Marine/marine.20190927.csv"

In [14]:
df = pd.read_csv(url, sep=";")

# 2) regarde des caractéristiques

## 2.1) nb de lignes et de colonnes

In [17]:
df.shape # nb de ligne, nb de colonnes

(166, 37)

## 2.2) entête

In [16]:
df.head(3)

,numer_sta,date,lat,lon,t,td,u,dd,ff,pmer,...,nbas,hbas,cl,cm,ch,rafper,per,phenspe1,phenspe2,Unnamed: 36
0,4100300,20190927000000,15.85,-57.49,302.050000,296.750000,73.000000,60.000000,5.200000,101500,...,mq,mq,mq,mq,mq,7.700000,-10,mq,mq,NaN
1,6100001,20190927000000,43.38,7.83,294.550000,292.650000,89.000000,80.000000,2.400000,101730,...,mq,mq,mq,mq,mq,4.000000,-10,mq,mq,NaN
2,6100002,20190927000000,42.06,4.65,295.150000,293.650000,91.000000,mq,mq,101820,...,mq,mq,mq,mq,mq,mq,-10,mq,mq,NaN

## 2.3) transposée => permet souvent de voir toutes les colonnes

In [18]:
df.head(3).T

                          0               1               2
numer_sta           4100300         6100001         6100002
date         20190927000000  20190927000000  20190927000000
lat                   15.85           43.38           42.06
lon                  -57.49            7.83            4.65
t                302.050000      294.550000      295.150000
td               296.750000      292.650000      293.650000
u                 73.000000       89.000000       91.000000
dd                60.000000       80.000000              mq
ff                 5.200000        2.400000              mq
pmer                 101500          101730          101820
tmer             302.650000      295.350000      294.950000
HwaHwa             1.300000        0.700000        0.600000
PwaPwa            10.000000        5.000000        3.000000
dwadwa                   mq              mq              mq
Hw1Hw1                   mq              mq              mq
Pw1Pw1                   mq              mq              mq
dw1dw1                   mq              mq              mq
Hw2Hw2                   mq              mq              mq
Pw2Pw2                   mq              mq              mq
dw2dw2                   mq              mq              mq
tend                     mq              mq              mq
cod_tend                 mq              mq              mq
vv                       mq              mq              mq
ww                       mq              mq              mq
w1                       mq              mq              mq
w2                       mq              mq              mq
n                        mq              mq              mq
nbas                     mq              mq              mq
hbas                     mq              mq              mq
cl                       mq              mq              mq
cm                       mq              mq              mq
ch                       mq              mq              mq
rafper             7.700000        4.000000              mq
per                     -10             -10             -10
phenspe1                 mq              mq              mq
phenspe2                 mq              mq              mq
Unnamed: 36             NaN             NaN             NaN

In [54]:
entetes = """Descriptif Mnémonique type unité
Indicatif OMM station numer_sta car
Date (UTC) date car AAAAMMDDHHMISS
Température t réel K
Point de rosée td réel K
Humidité u int %
Direction du vent moyen 10 mn dd int degré
Vitesse du vent moyen 10 mn ff réel  m/s
Pression au niveau mer pmer int Pa
Température de la mer tmer réel K
Hauteur des vagues de la mer du vent HwaHwa réel m
Période des vagues de la mer du vent PwaPwa réel S
Direction des vagues de la mer du vent dwadwa réel degré
Hauteur des vagues de la houle primaire Hw1Hw1 réel m
Période des vagues de la houle primaire Pw1Pw1 réel S
Direction des vagues de la houle primaire dw1dw1 réel degré
Hauteur des vagues de la houle secondaire Hw2Hw2 réel m
Période des vagues de la houle secondaire Pw2Pw2 réel S
Direction des vagues de la houle secondaire dw2dw2 réel degré
Variation de pression en 3 heures tend int Pa
Type de tendance barométrique cod_tend int code (0200)
Visibilité horizontale vv réel m
Temps présent ww int code (4677)
Temps passé 1 w1 int code (4561)
Temps passé 2 w2 int code (4561)
Nebulosité totale n réel %
Nébulosité des nuages de l'étage inférieur nbas int octa
Hauteur de la base des nuages de l'étage inférieur hbas int mètre
Type des nuages de l'étage inférieur cl int code (0513)
Type des nuages de l'étage moyen cm int code (0515)
Type des nuages de l'étage supérieur ch int code (0509)
Rafales sur une période  rafper réel m/s
Période de mesure de la rafale per réel min
Phénomène spécial phenspeN réel code (3778)"""

In [55]:
lignes_entetes = entetes.split("\n")

In [56]:
lignes_entetes

['Descriptif Mnémonique type unité',
 'Indicatif OMM station numer_sta car',
 'Date (UTC) date car AAAAMMDDHHMISS',
 'Température t réel K',
 'Point de rosée td réel K',
 'Humidité u int %',
 'Direction du vent moyen 10 mn dd int degré',
 'Vitesse du vent moyen 10 mn ff réel  m/s',
 'Pression au niveau mer pmer int Pa',
 'Température de la mer tmer réel K',
 'Hauteur des vagues de la mer du vent HwaHwa réel m',
 'Période des vagues de la mer du vent PwaPwa réel S',
 'Direction des vagues de la mer du vent dwadwa réel degré',
 'Hauteur des vagues de la houle primaire Hw1Hw1 réel m',
 'Période des vagues de la houle primaire Pw1Pw1 réel S',
 'Direction des vagues de la houle primaire dw1dw1 réel degré',
 'Hauteur des vagues de la houle secondaire Hw2Hw2 réel m',
 'Période des vagues de la houle secondaire Pw2Pw2 réel S',
 'Direction des vagues de la houle secondaire dw2dw2 réel degré',
 'Variation de pression en 3 heures tend int Pa',
 'Type de tendance barométrique cod_tend int code (0200)',
 'Visibilité horizontale vv réel m',
 'Temps présent ww int code (4677)',
 'Temps passé 1 w1 int code (4561)',
 'Temps passé 2 w2 int code (4561)',
 'Nebulosité totale n réel %',
 "Nébulosité des nuages de l'étage inférieur nbas int octa",
 "Hauteur de la base des nuages de l'étage inférieur hbas int mètre",
 "Type des nuages de l'étage inférieur cl int code (0513)",
 "Type des nuages de l'étage moyen cm int code (0515)",
 "Type des nuages de l'étage supérieur ch int code (0509)",
 'Rafales sur une période  rafper réel m/s',
 'Période de mesure de la rafale per réel min',
 'Phénomène spécial phenspeN réel code (3778)']

In [57]:
df_description = pd.DataFrame(lignes_entetes)

In [64]:
resultats = []
for ligne in lignes_entetes:
    dico = {}
    mots = ligne.split(" ")
    if "code" not in ligne:
        descriptif = " ".join(mots[:-3])
        Mnemonique = mots[-3]
        type_      = mots[-2]
        unite      = mots[-1]
    if "code" in ligne:
        descriptif = " ".join(mots[:-4])
        Mnemonique = mots[-4]
        type_      = mots[-3]
        unite      = " ".join(mots[-2:])
    dico["descriptif"] = descriptif
    dico["Mnemonique"] = Mnemonique
    dico["type_"] = type_
    dico["unite   "] = unite   
    resultats.append(dico)
pd.DataFrame(resultats)

,Mnemonique,descriptif,type_,unite
0,Mnémonique,Descriptif,type,unité
1,station,Indicatif OMM,numer_sta,car
2,date,Date (UTC),car,AAAAMMDDHHMISS
3,t,Température,réel,K
4,td,Point de rosée,réel,K
5,u,Humidité,int,%
6,dd,Direction du vent moyen 10 mn,int,degré
7,réel,Vitesse du vent moyen 10 mn ff,,m/s
8,pmer,Pression au niveau mer,int,Pa
9,tmer,Température de la mer,réel,K
10,HwaHwa,Hauteur des vagues de la mer du vent,réel,m
11,PwaPwa,Période des vagues de la mer du vent,réel,S
12,dwadwa,Direction des vagues de la mer du vent,réel,degré
13,Hw1Hw1,Hauteur des vagues de la houle primaire,réel,m
14,Pw1Pw1,Période des vagues de la houle primaire,réel,S
15,dw1dw1,Direction des vagues de la houle primaire,réel,degré
16,Hw2Hw2,Hauteur des vagues de la houle secondaire,réel,m
17,Pw2Pw2,Période des vagues de la houle secondaire,réel,S
18,dw2dw2,Direction des vagues de la houle secondaire,réel,degré
19,tend,Variation de pression en 3 heures,int,Pa
20,cod_tend,Type de tendance barométrique,int,code (0200)
21,vv,Visibilité horizontale,réel,m
22,ww,Temps présent,int,code (4677)
23,w1,Temps passé 1,int,code (4561)
24,w2,Temps passé 2,int,code (4561)
25,n,Nebulosité totale,réel,%
26,nbas,Nébulosité des nuages de l'étage inférieur,int,octa
27,hbas,Hauteur de la base des nuages de l'étage infér...,int,mètre
28,cl,Type des nuages de l'étage inférieur,int,code (0513)
29,cm,Type des nuages de l'étage moyen,int,code (0515)
30,ch,Type des nuages de l'étage supérieur,int,code (0509)
31,rafper,Rafales sur une période,réel,m/s
32,per,Période de mesure de la rafale,réel,min
33,phenspeN,Phénomène spécial,réel,code (3778)

In [62]:
pd.DataFrame(resultats)

,Mnemonique,descriptif,type_,unite
0,Mnémonique,Descriptif,type,unité
1,station,Indicatif OMM,numer_sta,car
2,date,Date (UTC),car,AAAAMMDDHHMISS
3,t,Température,réel,K
4,td,Point de rosée,réel,K
5,u,Humidité,int,%
6,dd,Direction du vent moyen 10 mn,int,degré
7,réel,Vitesse du vent moyen 10 mn ff,,m/s
8,pmer,Pression au niveau mer,int,Pa
9,tmer,Température de la mer,réel,K
10,HwaHwa,Hauteur des vagues de la mer du vent,réel,m
11,PwaPwa,Période des vagues de la mer du vent,réel,S
12,dwadwa,Direction des vagues de la mer du vent,réel,degré
13,Hw1Hw1,Hauteur des vagues de la houle primaire,réel,m
14,Pw1Pw1,Période des vagues de la houle primaire,réel,S
15,dw1dw1,Direction des vagues de la houle primaire,réel,degré
16,Hw2Hw2,Hauteur des vagues de la houle secondaire,réel,m
17,Pw2Pw2,Période des vagues de la houle secondaire,réel,S
18,dw2dw2,Direction des vagues de la houle secondaire,réel,degré
19,tend,Variation de pression en 3 heures,int,Pa
20,cod_tend,Type de tendance barométrique,int,code (0200)
21,vv,Visibilité horizontale,réel,m
22,ww,Temps présent,int,code (4677)
23,w1,Temps passé 1,int,code (4561)
24,w2,Temps passé 2,int,code (4561)
25,n,Nebulosité totale,réel,%
26,nbas,Nébulosité des nuages de l'étage inférieur,int,octa
27,hbas,Hauteur de la base des nuages de l'étage infér...,int,mètre
28,cl,Type des nuages de l'étage inférieur,int,code (0513)
29,cm,Type des nuages de l'étage moyen,int,code (0515)
30,ch,Type des nuages de l'étage supérieur,int,code (0509)
31,rafper,Rafales sur une période,réel,m/s
32,per,Période de mesure de la rafale,réel,min
33,phenspeN,Phénomène spécial,réel,code (3778)